"""fix created_at not null

Revision ID: b3a2b520c2f3
Revises: 572c67685a5a
Create Date: 2026-02-21 12:58:22.758456

"""
from typing import Sequence, Union
from sqlalchemy import text
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3a2b520c2f3'
down_revision: Union[str, Sequence[str], None] = '572c67685a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1️⃣ Fill NULL values first
    op.execute(
        text(
            "UPDATE tags SET created_at = NOW() WHERE created_at IS NULL"
        )
    )

    # 2️⃣ Then set NOT NULL
    op.alter_column(
        "tags",
        "created_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
